#!/usr/bin/env bash

if [ "$(whoami)" != "root" ]; then
  echo "You must be sudo or root to run this script."
  exit 1
fi

mkdir -p /web/tld/sandbox/lab/domain
cd /web/tld/sandbox/lab/domain
touch index.php
echo "OK" >> index.php

echo -e "\n\n
address=/dev/127.0.0.1
\n\n" >> /etc/NetworkManager/dnsmasq.d/dev.conf

service network-manager restart

echo -e "\n\n
NameVirtualHost *:80

# devTLD

<VirtualHost *:80>
    ServerName              dev
    VirtualDocumentRoot     /web/tld/sandbox/lab/domain
</VirtualHost>

# ccTLDs (e.g. com.au, co.uk, ...)
<VirtualHost *:80>
    ServerName              cctld.cctld.dev
    ServerAlias             *.*.*.co.uk.dev *.*.*.com.au.dev
    VirtualDocumentRoot     /web/%-2.0.%-3.0/%-4/%-5/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              cctld.cctld.dev
    ServerAlias             *.*.co.uk.dev *.*.com.au.dev
    VirtualDocumentRoot     /web/%-2.0.%-3.0/%-4/%-5/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              cctld.cctld.dev
    ServerAlias             *.co.uk.dev *.com.au.dev
    VirtualDocumentRoot     /web/%-2.0.%-3.0/%-4/lab/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              cctld.cctld.dev
    ServerAlias             co.uk.dev com.au.dev
    VirtualDocumentRoot     /web/%-2.0.%-3.0/sandbox/lab/domain
</VirtualHost>

# gTLDs (e.g. com, net, ...)

<VirtualHost *:80>
    ServerName              gtld.dev
    ServerAlias             *.*.*.*.dev
    VirtualDocumentRoot     /web/%-2/%-3/%-4/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              gtld.dev
    ServerAlias             *.*.*.dev
    VirtualDocumentRoot     /web/%-2/%-3/%-4/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              gtld.dev
    ServerAlias             *.*.dev
    VirtualDocumentRoot     /web/%-2/%-3/lab/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              gtld.dev
    ServerAlias             *.dev
    VirtualDocumentRoot     /web/%-2/sandbox/lab/domain
</VirtualHost>
\n\n" >> /etc/apache2/sites-available/zzz-wildcard.conf
a2ensite zzz-wildcard.conf
a2enmod vhost_alias
a2enmod rewrite
a2enmod expires
a2enmod headers
service apache2 restart

echo "Script complete."
exit
