#!/usr/bin/env bash

################################################################################
# Check that this script is being run with elevated privileges.
################################################################################

if [ "$(whoami)" != "root" ]; then
  echo "You must be sudo or root to run this script."
  exit 1
fi

################################################################################
# Create web directories.
################################################################################

mkdir -p -m 2775 /web/tld/sandbox/{api,assets,lab,www}/{domain,engine,source,system}
chown -R $SUDO_USER:www-data /web

################################################################################
# Configure DNSMasq.
################################################################################

echo "
address=/dev/127.0.0.1
" >> /etc/NetworkManager/dnsmasq.d/dev.conf

################################################################################
# Create wildcard fallback configuration for Apache2.
################################################################################
echo "
<Directory /web>
    Require All Granted
</Directory>

# devTLD

<VirtualHost *:80>
    ServerName              dev
    VirtualDocumentRoot     /web/tld/sandbox/lab/domain
</VirtualHost>

# ccTLDs (e.g. com.au, co.uk, ...)
<VirtualHost *:80>
    ServerName              cctld.cctld.dev
    ServerAlias             *.*.*.co.uk.dev *.*.*.com.au.dev
    VirtualDocumentRoot     /web/%-2.0.%-3.0/%-4/%-5/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              cctld.cctld.dev
    ServerAlias             *.*.co.uk.dev *.*.com.au.dev
    VirtualDocumentRoot     /web/%-2.0.%-3.0/%-4/%-5/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              cctld.cctld.dev
    ServerAlias             *.co.uk.dev *.com.au.dev
    VirtualDocumentRoot     /web/%-2.0.%-3.0/%-4/lab/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              cctld.cctld.dev
    ServerAlias             co.uk.dev com.au.dev
    VirtualDocumentRoot     /web/%-2.0.%-3.0/sandbox/lab/domain
</VirtualHost>

# gTLDs (e.g. com, net, ...)

<VirtualHost *:80>
    ServerName              gtld.dev
    ServerAlias             *.*.*.*.dev
    VirtualDocumentRoot     /web/%-2/%-3/%-4/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              gtld.dev
    ServerAlias             *.*.*.dev
    VirtualDocumentRoot     /web/%-2/%-3/%-4/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              gtld.dev
    ServerAlias             *.*.dev
    VirtualDocumentRoot     /web/%-2/%-3/lab/domain
</VirtualHost>
<VirtualHost *:80>
    ServerName              gtld.dev
    ServerAlias             *.dev
    VirtualDocumentRoot     /web/%-2/sandbox/lab/domain
</VirtualHost>
" >> /etc/apache2/sites-available/zzz-wildcard.conf

################################################################################
# Enable wildcard fallback configuration and some Apache2 modules.
################################################################################

a2ensite zzz-wildcard.conf
a2enmod vhost_alias
a2enmod rewrite
a2enmod expires
a2enmod headers

################################################################################
# Restart services.
################################################################################

service network-manager restart
service apache2 restart

################################################################################
# Script completed successfully.
################################################################################

echo "Script completed successfully."
exit
